---
- name: install keylime
  hosts: all
  remote_user: fedora
  become: true

  tasks:
    - name: install keylime and its dependencies
      dnf:
        name: '{{ item }}'
        state: present
      loop:
        - keylime
        - wget
        - gcc
        - make
        - openssl-devel
        - vim
        - iputils
