---
- name: install keylime
  hosts: all
  remote_user: fedora
  become: true

  tasks:
    - name: install keylime and its dependencies
      tags: keylime
      dnf:
        name: '{{ item }}'
        state: latest
        update_cache: yes
      loop:
        - keylime
        - wget
        - gcc
        - make
        - openssl-devel
        - vim
        - iputils

- name: install swtpm
  hosts: agents
  remote_user: fedora
  become: true

  tasks:
    - name: install swtpm and its dependencies
      tags: swtpm
      dnf:
        name: '{{ item }}'
        state: latest
        update_cache: yes
      loop:
        - dbus
        - dbus-daemon
        - dbus-devel
        - swtpm
        - swtpm-tools
