---
- name: install keylime
  hosts: all
  remote_user: fedora
  become: true

  tasks:
    - name: install keylime and its dependencies
      tags: keylime_agent
      dnf:
        name: '{{ item }}'
        state: latest
        update_cache: yes
      loop:
        - keylime
        - wget
        - gcc
        - make
        - openssl-devel
        - vim
        - iputils

- name: install swtpm
  hosts: agents
  remote_user: fedora
  become: true

  tasks:
    - name: install swtpm and its dependencies
      tags: swtpm,keylime_agent
      dnf:
        name: '{{ item }}'
        state: latest
        update_cache: yes
      loop:
        - dbus
        - dbus-daemon
        - dbus-devel
        - swtpm
        - swtpm-tools

    - name: copy swtpm bootstrap script
      tags: swtpm,keylime_agent
      copy:
        src: swtpm.sh
        dest: /root/swtpm.sh
        owner: root
        group: root
        mode: 0755

    - name: customize keylime agent ip
      tags: keylime_agent,keylime_agent_config
      lineinfile:
        path: /etc/keylime.conf
        regexp: '^cloudagent_ip = *'
        replace: cloudagent_ip = 0.0.0.0
        firstmatch: yes

    - name: set require_ek_cert to false
      tags: keylime_agent,keylime_agent_config
      lineinfile:
        path: /etc/keylime.conf
        regexp: '^require_ek_cert = *'
        replace: require_ek_cert = False
        firstmatch: yes

    - name: customize keylime registrar ip
      tags: keylime_agent,keylime_agent_config
      lineinfile:
        path: /etc/keylime.conf
        regexp: '^registrar_ip = 127.0.0.1$'
        replace: registrar_ip = '{{ registrar_ip }}'
        firstmatch: yes
